name = "demo-stm32h723-nucleo"
target = "thumbv7em-none-eabihf"
board = "nucleo-h723zg"
chip = "../../chips/stm32h7.toml"
stacksize = 896

[kernel]
path = "."
name = "demo-stm32h7-nucleo"
requires = {flash = 21376, ram = 4096}

#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["h723", "itm"]


[supervisor]
notification = 1

# Flash sections are mapped into flash bank 1 (of 2).
[outputs.flash]
address = 0x08000000
size = 1048576
read = true
execute = true

# RAM sections are currently mapped into DTCM, a small but fast SRAM.
[outputs.ram]
address = 0x20000000
size = 131072
read = true
write = true
execute = false  # let's assume XN until proven otherwise

# Network buffers are placed in sram1, which is directly accessible by the
# Ethernet MAC.
[outputs.sram1]
address = 0x30000000
size = 0x20000
read = true
write = true
dma = true


[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.sys]
path = "../../drv/stm32xx-sys"
name = "drv-stm32xx-sys"
features = ["h723"]
priority = 1
requires = {flash = 2048, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3"]
start = true

[tasks.user_leds]
path = "../../drv/user-leds"
name = "drv-user-leds"
features = ["stm32h7"]
priority = 2
requires = {flash = 2048, ram = 1024}
start = true
task-slots = ["sys"]

[tasks.ping]
path = "../../task/ping"
name = "task-ping"
features = []
priority = 4
requires = {flash = 8192, ram = 1024}
start = true
task-slots = [{peer = "pong"}]

[tasks.pong]
path = "../../task/pong"
name = "task-pong"
priority = 3
requires = {flash = 1024, ram = 1024}
start = true
task-slots = ["user_leds"]

[tasks.hiffy]
path = "../../task/hiffy"
name = "task-hiffy"
features = ["h723", "stm32h7", "itm", "gpio"]
priority = 3
requires = {flash = 32768, ram = 32768 }
stacksize = 2048
start = true
task-slots = ["sys"]

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 128, ram = 256}
stacksize = 256
start = true
