[package]
name = "drv-lpc55-gpio"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
lpc55-pac = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
drv-lpc55-gpio-api = {path = "../lpc55-gpio-api"}
drv-lpc55-syscon-api = {path = "../lpc55-syscon-api"}
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}
zerocopy = "0.6.1"

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-lpc55-gpio"
test = false
bench = false
